# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ZXPageScrollView+CycleView+CategoryView' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'MJExtension’
  pod 'SDWebImage'
  pod 'MBProgressHUD', '~> 0.9.1'
  pod 'MJRefresh', '~> 2.4.10'
  pod 'Toast', '~> 3.0'
  pod 'ReactiveCocoa', '~> 2.5'
  pod 'YYKit'

end
